Margento

Google & Margento--War in Ukraine

google search: ukraine war poem

In [1]:
import os
#The OS module in Python provides a way of using operating system dependent functionality. 
#The functions that the OS module provides allows you to interface with the underlying operating system 
#that Python is running on – be that Windows, Mac or Linux.

from os import listdir
from os.path import isfile, join
import nltk
#import logging
#Module that records events related to the application’s operation. 
#The log record, which is created with every logging event, contains readily available diagnostic information such as 
#the file name, full path, function, and line number of the logging event.

#from collections import Counter
#from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
#sklearn implements support vector classification; it is part of 
#scikit-learn, a free software machine learning library for Python (tools for data mining and data analysis)

import networkx as nx
import matplotlib.pyplot as plt  
import numpy as np
#logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s',
                    #level=logging.INFO)
#nltk.download('popular', halt_on_error=False)

import re
import codecs
import string
from string import punctuation

In [2]:
pwd

'/Users/christanasescu'

In [3]:
stopwords = nltk.corpus.stopwords.words('stop_words_poetry.txt')

stopwords.append('...')
stopwords.append("'d")
stopwords.append('...')
stopwords.append("&")
stopwords.append("upon")
stopwords.append("also")
stopwords.append("hath")
stopwords.append("must")
stopwords.append("therefore")
stopwords.append("doth")
stopwords.append("could")
stopwords.append("would")
#stopwords.append("another")
stopwords.append("much")
#stopwords.append("give")
stopwords.append("like")
stopwords.append("since")
#stopwords.append("many")
#stopwords.append("without")
#stopwords.append("first")
stopwords.append("though")
#stopwords.append("well")
#stopwords.append("often")
#stopwords.append("great")
stopwords.append("either")
#stopwords.append("even")
stopwords.append("shall")
#stopwords.append("they")
stopwords.append("what")
stopwords.append("their")
#stopwords.append("more")
#stopwords.append("there")
#stopwords.append("your")
#stopwords.append("them")
stopwords.append("’")
stopwords.append("“")
stopwords.append("2")
stopwords.append("3")
stopwords.append("”")

In [4]:
def _pre_clean(list_of_text):
        '''
        preliminary cleaning of the text
        - remove new line character i.e. \n or \r
        - remove tabs i.e. \t
        - remove extra spaces
        '''
        cleaned_list = []
        for text in list_of_text:
            # print("original:", text)
            text = text.replace('\\n', ' ')
            text = text.replace('\\r', ' ')
            text = text.replace('\\t', ' ')
            pattern = re.compile(r'\s+')
            text = re.sub(pattern, ' ', text)
            text = text.strip()
            # check for empty strings
            if text != '' and text is not None:
                cleaned_list.append(text)

        return cleaned_list

In [5]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [6]:
def tokenize(text):
    tokens = word_tokenize(text)
    tokens = _pre_clean(tokens)
    tokens = [token for token in tokens if len(token) > 2]
    tokens = [token for token in tokens if token not in stopwords]
    #tokens = [get_lemma(token) for token in tokens]
    return tokens

In [7]:
HOME = os.getcwd()

TEXTS_DIR = HOME + "/fastText_multilingual-master/war_in_ukraine/"

#TEXTS_DIR = HOME

filelabels = {}

texts_data = []

files = [f for f in os.listdir(TEXTS_DIR) if os.path.isfile(os.path.join(TEXTS_DIR, f))]

import string
from string import punctuation

remove_punct_map = dict.fromkeys(map(ord, string.punctuation))

tokens_total = []

count = -1
 
os.chdir(TEXTS_DIR)
    
for f in files:
    #os.chdir(TEXTS_DIR)
    with open(f, "r", encoding='utf-8', errors = 'ignore') as openf:
        tokens = []
        count = count + 1
        filelabels[count] = os.path.basename(openf.name)
        for line in openf:
            sent_text = nltk.sent_tokenize(line)
            for sentence in sent_text:
                tokens1 = tokenize(sentence)
                tokens1 = [item.translate(remove_punct_map)
                      for item in tokens1]
                #filter_object = filter(lambda x: x != "", tokens1)
                tokens1 = [x for x in tokens1 if x!= ""]
                tokens1 = [x.lower() for x in tokens1]
                for token in tokens1:
                    tokens.append(token)
                    tokens_total.append(token)
                #if random.random() > .99:
                #print(tokens)
    #print(tokens_total)
    texts_data.append(tokens)

print(filelabels)

{0: '00_annalyne_poem_to_putin.txt', 1: '01_russian_poet_arrested.txt', 2: '02_new_yorker_news.txt', 3: '03_celebrities_go_full_cringe.txt', 4: '04_ukraine_feature_pio.txt', 5: '05_ukrainian_lit.txt', 6: '06_olivia_wilde.txt', 7: '07_kobzar.txt', 8: '08_lesson_of_the_day.txt', 9: '09_ukrainian_needs_prayers.txt', 10: '10_transreading_russia.txt', 11: '11_ukraine_tls.txt', 12: '12_calamity_again.txt', 13: '13_war_advertisement.txt', 14: '14_putin_on_history_literature.txt', 15: '15_fakes_about_the_invasion.txt', 16: '16_poetry_of_war.txt', 17: '17_maps_&_poems.txt', 18: '18_massacre.txt', 19: '19_myroslav_laiuk.txt', 20: '20_ukrainian_lit_in_en.txt', 21: '21_songs.txt', 22: '22_special_operation.txt', 23: '23_jewish_poets.txt', 24: '24_holodomor.txt', 25: '25_surrender?.txt', 26: '26_poet_charged.txt', 27: '27_love_in_kyiv.txt', 28: '28_unlawful.txt', 29: '29_musk_tweets_poems.txt', 30: '30_bell_hooks.txt', 31: '31_tracy_k_smith.txt', 32: '32_poem_hunter.txt', 33: '33_twitter_poem.txt',

In [8]:
# We are using the poems in the computationally assembled anthology MARGENTO (eds.) "US" Poets Foreign Poets
# https://www.asymptotejournal.com/blog/2019/01/24/us-poets-foreign-poets-a-computationally-assembled-anthology/ 
# https://www.asymptotejournal.com/blog/2019/05/30/our-shared-world-of-language-reflections-on-us-poets-foreign-poets/
# https://www.academia.edu/41440906/_US_Poets_Foreign_Poets_A_Computationally_Assembled_Anthology_MARGENTO

In [8]:
stopwords.extend(['a', 'like', 'you', 'they', 'he', 'be', 'it', 'your', 'her', 'of', 'more', 'there', 'no', 'not', '’', 'what', 'my', 'his', 'she', 'to', 'our', 'me', 'we', 'in', 'can', 'us', 'an', 'if', 'do', 'this', '”', 'because', 'who', 'and', 'but', 'him'])

In [9]:
tokens_total = [x for x in tokens_total if x not in stopwords]

In [11]:

for i in range(len(filelabels)):
    print(len(texts_data[i]))

14
15
20
12
22
21
14
21
18
24
19
21
20
23
14
23
18
21
22
15
12
24
17
11
14
17
28
20
28
17
22
19
19
11
20
15
16


In [10]:
for i in range(len(filelabels)):
    texts_data[i] = [x for x in texts_data[i] if x not in stopwords]

In [13]:
#for i in range(len(filelabels)):
    #print(len(texts_data[i]))

In [ ]:

# Topic modeling does not make sense [which we should have expected]

In [11]:
def get_documents(path):
    os.chdir(path)
    files = [f for f in listdir(path) if isfile(join(path, f))]
    texts = []
    count = -1
    for f in files:
        with codecs.open(f, "r", encoding='utf-8', errors = 'ignore') as openf:
            count = count + 1
            filelabels[count] = os.path.basename(openf.name)
            splitted_lines = openf.read().splitlines()
            splitted_lines = _pre_clean(splitted_lines)
            texts.append(splitted_lines)
    #print(filelabels)
    return texts

In [12]:
documents = get_documents(TEXTS_DIR)

In [13]:
exclude = set(punctuation)

In [14]:
new_documents = []

for document in documents:
    new_document = ""
    for string_ in document:
        exclude = set(string.punctuation)
        string_ = ''.join(ch for ch in string_ if ch not in exclude)
        lower_string = string_.lower()
        new_document = " ".join([new_document, lower_string]) 
    new_documents.append(new_document)
     

In [18]:
#print(documents[36])

In [19]:
#print(new_documents[36])

In [20]:
#print(documents[33])

In [21]:
#print(new_documents[33])

In [15]:

from sklearn.feature_extraction.text import CountVectorizer

In [16]:

vectorizer = CountVectorizer(new_documents, stop_words = stopwords)

In [17]:
X = vectorizer.fit_transform(new_documents)

In [25]:
X.shape

(37, 444)

In [18]:
Y = X.toarray()

from sklearn.feature_extraction.text import TfidfTransformer

tf_idf_vect = TfidfVectorizer(stop_words = stopwords)

tfidf = tf_idf_vect.fit_transform(new_documents)

#print(type(tfidf))

W = tfidf.toarray()

#print(type(W))

dt = [('correlation', float)]

similarity_matrix = np.matrix((tfidf * tfidf.T).A, dtype=dt)

import networkx as nx

G = nx.from_numpy_matrix(similarity_matrix)

weights = [(G[tpl[0]][tpl[1]]['correlation']) for tpl in G.edges()]


In [19]:
e = [(x, x) for x in G.nodes()] 

G.remove_edges_from(e)


In [28]:

similarity_matrix[range(len(filelabels)), range(len(filelabels))]

matrix([[(1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,),
         (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,),
         (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,),
         (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,), (1.,),
         (1.,)]], dtype=[('correlation', '<f8')])

In [20]:

similarity_matrix[range(len(filelabels)), range(len(filelabels))] = 0

In [30]:
similarity_matrix.shape

(37, 37)

In [21]:

SAM = np.zeros(shape=(2*len(filelabels), 2*len(filelabels)))

In [32]:
print(SAM)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:

sim_0 = np.array(similarity_matrix)

In [34]:

print(sim_0)

[[(0.        ,) (0.        ,) (0.        ,) ... (0.        ,)
  (0.        ,) (0.        ,)]
 [(0.        ,) (0.        ,) (0.04679713,) ... (0.03881888,)
  (0.05178745,) (0.        ,)]
 [(0.        ,) (0.04679713,) (0.        ,) ... (0.05674513,)
  (0.04351378,) (0.        ,)]
 ...
 [(0.        ,) (0.03881888,) (0.05674513,) ... (0.        ,)
  (0.02074594,) (0.        ,)]
 [(0.        ,) (0.05178745,) (0.04351378,) ... (0.02074594,)
  (0.        ,) (0.        ,)]
 [(0.        ,) (0.        ,) (0.        ,) ... (0.        ,)
  (0.        ,) (0.        ,)]]


In [35]:
sim_0.shape

(37, 37)

In [36]:
SAM.shape

(74, 74)

In [37]:
sim_0[0][0][0]

0.0

In [38]:
sim_0[0][0][0]

0.0

In [39]:
sim_0[0][1][0]

0.0

In [23]:

for i in range(len(filelabels)):
    for j in range(len(filelabels)):
        SAM[i][j] = sim_0[i][j][0]

In [41]:

SAM[0][1]

0.0

In [42]:
SAM[1][2]

0.04679713450038443

In [24]:
import numpy as np

import scipy

In [25]:
class FastVector:
    """
    Minimal wrapper for fastvector embeddings.
    ```
    Usage:
        $ model = FastVector(vector_file='/path/to/wiki.en.vec')
        $ 'apple' in model
        > TRUE
        $ model['apple'].shape
        > (300,)
    ```
    """

    def __init__(self, vector_file='', transform=None):
        """Read in word vectors in fasttext format"""
        self.word2id = {}

        # Captures word order, for export() and translate methods
        self.id2word = []

        print('reading word vectors from %s' % vector_file)
        with open(vector_file, 'r') as f:
            (self.n_words, self.n_dim) = \
                (int(x) for x in f.readline().rstrip('\n').split(' '))
            self.embed = np.zeros((self.n_words, self.n_dim))
            for i, line in enumerate(f):
                elems = line.rstrip('\n').split(' ')
                self.word2id[elems[0]] = i
                self.embed[i] = elems[1:self.n_dim+1]
                self.id2word.append(elems[0])
        
        # Used in translate_inverted_softmax()
        self.softmax_denominators = None
        
        if transform is not None:
            print('Applying transformation to embedding')
            self.apply_transform(transform)

    def apply_transform(self, transform):
        """
        Apply the given transformation to the vector space
        Right-multiplies given transform with embeddings E:
            E = E * transform
        Transform can either be a string with a filename to a
        text file containing a ndarray (compat. with np.loadtxt)
        or a numpy ndarray.
        """
        transmat = np.loadtxt(transform) if isinstance(transform, str) else transform
        self.embed = np.matmul(self.embed, transmat)

    def export(self, outpath):
        """
        Transforming a large matrix of WordVectors is expensive. 
        This method lets you write the transformed matrix back to a file for future use
        :param The path to the output file to be written 
        """
        fout = open(outpath, "w")

        # Header takes the guesswork out of loading by recording how many lines, vector dims
        fout.write(str(self.n_words) + " " + str(self.n_dim) + "\n")
        for token in self.id2word:
            vector_components = ["%.6f" % number for number in self[token]]
            vector_as_string = " ".join(vector_components)

            out_line = token + " " + vector_as_string + "\n"
            fout.write(out_line)

        fout.close()

    def translate_nearest_neighbour(self, source_vector):
        """Obtain translation of source_vector using nearest neighbour retrieval"""
        similarity_vector = np.matmul(FastVector.normalised(self.embed), source_vector)
        target_id = np.argmax(similarity_vector)
        return self.id2word[target_id]

    def translate_inverted_softmax(self, source_vector, source_space, nsamples,
                                   beta=10., batch_size=100, recalculate=True):
        """
        Obtain translation of source_vector using sampled inverted softmax retrieval
        with inverse temperature beta.
        nsamples vectors are drawn from source_space in batches of batch_size
        to calculate the inverted softmax denominators.
        Denominators from previous call are reused if recalculate=False. This saves
        time if multiple words are translated from the same source language.
        """
        embed_normalised = FastVector.normalised(self.embed)
        # calculate contributions to softmax denominators in batches
        # to save memory
        if self.softmax_denominators is None or recalculate is True:
            self.softmax_denominators = np.zeros(self.embed.shape[0])
            while nsamples > 0:
                # get batch of randomly sampled vectors from source space
                sample_vectors = source_space.get_samples(min(nsamples, batch_size))
                # calculate cosine similarities between sampled vectors and
                # all vectors in the target space
                sample_similarities = \
                    np.matmul(embed_normalised,
                              FastVector.normalised(sample_vectors).transpose())
                # accumulate contribution to denominators
                self.softmax_denominators \
                    += np.sum(np.exp(beta * sample_similarities), axis=1)
                nsamples -= batch_size
        # cosine similarities between source_vector and all target vectors
        similarity_vector = np.matmul(embed_normalised,
                                      source_vector/np.linalg.norm(source_vector))
        # exponentiate and normalise with denominators to obtain inverted softmax
        softmax_scores = np.exp(beta * similarity_vector) / \
                         self.softmax_denominators
        # pick highest score as translation
        target_id = np.argmax(softmax_scores)
        return self.id2word[target_id]

    def get_samples(self, nsamples):
        """Return a matrix of nsamples randomly sampled vectors from embed"""
        sample_ids = np.random.choice(self.embed.shape[0], nsamples, replace=False)
        return self.embed[sample_ids]

    @classmethod
    def normalised(cls, mat, axis=-1, order=2):
        """Utility function to normalise the rows of a numpy array."""
        norm = np.linalg.norm(
            mat, axis=axis, ord=order, keepdims=True)
        norm[norm == 0] = 1
        return mat / norm
    
    @classmethod
    def cosine_similarity(cls, vec_a, vec_b):
        """Compute cosine similarity between vec_a and vec_b"""
        return np.dot(vec_a, vec_b) / \
            (np.linalg.norm(vec_a) * np.linalg.norm(vec_b))

    def __contains__(self, key):
        return key in self.word2id

    def __getitem__(self, key):
        return self.embed[self.word2id[key]]

In [26]:
def normalized(a, axis=-1, order=2):
    """Utility function to normalize the rows of a numpy array."""
    l2 = np.atleast_1d(np.linalg.norm(a, order, axis))
    l2[l2==0] = 1
    return a / np.expand_dims(l2, axis)

def make_training_matrices(source_dictionary, target_dictionary, bilingual_dictionary):
    """
    Source and target dictionaries are the FastVector objects of
    source/target languages. bilingual_dictionary is a list of 
    translation pair tuples [(source_word, target_word), ...].
    """
    source_matrix = []
    target_matrix = []

    for (source, target) in bilingual_dictionary:
        if source in source_dictionary and target in target_dictionary:
            source_matrix.append(source_dictionary[source])
            target_matrix.append(target_dictionary[target])

    # return training matrices
    return np.array(source_matrix), np.array(target_matrix)

def learn_transformation(source_matrix, target_matrix, normalize_vectors=True):
    """
    Source and target matrices are numpy arrays, shape
    (dictionary_length, embedding_dimension). These contain paired
    word vectors from the bilingual dictionary.
    """
    # optionally normalize the training vectors
    if normalize_vectors:
        source_matrix = normalized(source_matrix)
        target_matrix = normalized(target_matrix)

    # perform the SVD
    product = np.matmul(source_matrix.transpose(), target_matrix)
    U, s, V = np.linalg.svd(product)

    # return orthogonal transformation which aligns source language to the target
    return np.matmul(U, V)

In [32]:

cd /Users/christanasescu/fastText_multilingual-master

/Users/christanasescu/fastText_multilingual-master


In [33]:

en_dictionary = FastVector(vector_file='wiki.en.vec')

reading word vectors from wiki.en.vec


In [34]:

en_words = set(en_dictionary.word2id.keys())

In [35]:

en_words = list(en_words)

In [81]:
pwd

'/Users/christanasescu/fastText_multilingual-master/war_in_ukraine'

In [84]:
cd ..

/Users/christanasescu/fastText_multilingual-master


In [85]:

HOME = os.getcwd()

TEXTS_DIR = HOME + "/war_in_ukraine/"
#Poems_Dir = HOME

os.chdir(TEXTS_DIR)
lines = [i for i in range(len(filelabels))]

files = [f for f in os.listdir(TEXTS_DIR) if os.path.isfile(os.path.join(TEXTS_DIR, f))]

i = -1


#for i in range(len(filelabels)):
    #lines_1 = []
    #with open (List_poem_itinerary[i][1], 'rt') as file:
for f in files:
    with open(f, "r", encoding='utf-8', errors = 'ignore') as openf:
        lines_1 = []
        i = i + 1
        filelabels[count] = os.path.basename(openf.name)
        for line in openf:
        #for line in file:
                line = line.replace('\\n', ' ')
                line = line.replace('\\r', ' ')
                line = line.replace('\\t', ' ')
                pattern = re.compile(r'\s+')
                line = re.sub(pattern, ' ', line)
                line = line.strip()
                line = line.lower()
                # check for empty strings
                if line != '' and line is not None:
                    lines_1.append(line)
        lines[i] = lines_1
    

In [51]:
lines[0]

['annalynne mccord has recited a poem to president putin',
 'if i was your mother, the world would have been warm / so much laughter and joy and nothing would harm']

In [37]:

poems_tokens = []

for i in range(len(lines)):
    poems_tokens.append(lines[i])

In [38]:

for i in range(len(lines)):
    for j in range(len(lines[i])):
        tokens = []
        tokens1 = tokenize(lines[i][j])
        tokens1 = [item.translate(remove_punct_map)
                      for item in tokens1]
        tokens1 = [x for x in tokens1 if x!= ""]
        for token in tokens1:
                    tokens.append(token)
        poems_tokens[i][j] = tokens

In [39]:

for i in range(len(poems_tokens)):
        for j in range(len(poems_tokens[i])):
            poems_tokens[i][j] = [x for x in poems_tokens[i][j] if x not in stopwords]

In [55]:

poems_tokens[36]

[['antiwar', 'demo', 'cathedra', 'markt', 'frozen', 'crowd', 'online', 'ant'],
 ['antwerp',
  'twerp',
  'crawling',
  'indoor',
  'cafes',
  'away',
  'calculated',
  'sun']]

In [40]:

vectors_of_lines = []

In [41]:

for i in range(len(poems_tokens)):
    vectors_of_lines.append(poems_tokens[i])

In [42]:

def l2_norm(x):
   return np.sqrt(np.sum(x**2))

def div_norm(x):
   norm_value = l2_norm(x)
   if norm_value > 0:
       return x * ( 1.0 / norm_value)
   else:
       return x

In [43]:

for i in range(len(poems_tokens)):
    vectors_of_lines[i] = []
    #if i % 2 == 0:
    for j in range(len(poems_tokens[i])):
            vect1 = []
            for k in range(len(poems_tokens[i][j])):
                    if poems_tokens[i][j][k] in en_words:
                        vect1.append(div_norm(en_dictionary[poems_tokens[i][j][k]]))
                    else:
                        continue
            if len(poems_tokens[i][j]) != 0:
                vect0 = sum(vect1) / len(poems_tokens[i][j])
            else:
                vect0 = 0
            vectors_of_lines[i].append((j, vect0))

In [60]:

vectors_of_lines[4]

[(0,
  array([-6.94155203e-04, -1.61414387e-02, -1.91115497e-02,  3.23625525e-02,
         -1.50783822e-02,  1.42198745e-02,  2.56544786e-03, -1.87598274e-02,
         -8.40242078e-03,  3.15030796e-02, -1.49848870e-02, -1.55002940e-03,
         -3.36727376e-02, -1.00805578e-02,  7.76782880e-03, -2.60345033e-02,
          1.94894255e-02,  2.96792092e-02,  4.27760069e-02,  6.64073312e-02,
         -2.70787235e-02,  3.62550934e-02, -5.25584264e-02, -2.31899221e-02,
          2.28988049e-02, -2.17851858e-02, -3.35879615e-02,  1.00521742e-02,
          4.01690490e-02,  2.41565466e-02, -9.05675738e-03,  8.00670029e-02,
         -4.73933558e-02,  1.14361067e-02,  1.09559305e-02, -1.26858285e-02,
          3.60750935e-03, -6.07972741e-03,  7.48561115e-02, -1.08029345e-02,
          4.20380425e-03,  8.74910938e-03,  1.01369872e-03,  3.52562248e-02,
          1.08907284e-02, -1.43620030e-02,  4.14647146e-02,  4.97246538e-03,
          4.88153062e-03, -7.68878862e-03,  2.23933845e-02, -3.80065547

In [61]:

poems_tokens[4]

[['poetry',
  'interrupt',
  'ukraine',
  'invasion',
  'breaking',
  'news',
  'applebee'],
 ['literally',
  'dancing',
  'cowboy',
  'care',
  'next',
  'russia',
  'invades',
  'ukraine',
  'banner',
  'unfortunate',
  'juxtaposition',
  'nightmare',
  'advertisers']]

In [62]:

vectors_of_lines[30]

[(0,
  array([-0.0248435 ,  0.00289008,  0.0081701 ,  0.03408529, -0.02961566,
          0.00961857, -0.00237798, -0.01614437,  0.01727663,  0.04069366,
          0.04725029,  0.04735925,  0.0110001 , -0.00230699, -0.01501697,
         -0.02970825,  0.02158169,  0.02287983,  0.05006909,  0.06047099,
         -0.01420604,  0.05101112, -0.04351609, -0.03165736,  0.03028389,
         -0.04018218,  0.01470897, -0.02829269,  0.06554529,  0.02702795,
         -0.04073085,  0.05149144, -0.03657273,  0.02932359,  0.0144959 ,
          0.00773226, -0.03552485,  0.02774676,  0.0525759 , -0.0100171 ,
          0.00188385, -0.03376595,  0.04151331,  0.01033899, -0.01032549,
         -0.00526202,  0.00134311, -0.0100283 ,  0.00674086, -0.03803946,
          0.01386025, -0.01791923,  0.01233035,  0.0050413 , -0.04760404,
          0.00211408,  0.02396639,  0.02994179,  0.00221273,  0.02372354,
          0.02124269,  0.04442902,  0.03688224,  0.00074273,  0.00260212,
         -0.01268472, -0.0308846 

In [44]:

poem_meter = [0] * len(vectors_of_lines)

In [45]:

for i in range(len(vectors_of_lines)):
    poem_meter[i] = []
    #if i % 2 == 0:
    for j in range(len(vectors_of_lines[i])):
            vect1 = []
            vect1.append(vectors_of_lines[i][j][1])
    poem_meter[i] = sum(vect1) / len(vectors_of_lines[i])

In [65]:
#similarity_matrix_1 = np.matrix((poem_meter * poem_meter.T).A, dtype=dt)

AttributeError: 'list' object has no attribute 'T'

In [46]:
meters = np.asmatrix(poem_meter)

In [47]:

similarity_matrix_1 = np.matrix((meters * meters.T).A, dtype=dt)

In [48]:

similarity_matrix_1[range(len(filelabels)), range(len(filelabels))] = 0

In [49]:

sim_1 = np.array(similarity_matrix_1)

In [50]:

for i in range(len(filelabels)):
    for j in range(len(filelabels)):
        SAM[i + len(filelabels)][j + len(filelabels)] = sim_1[i][j][0]

In [51]:

G1 = nx.from_numpy_matrix(similarity_matrix_1)

weights_1 = [(G1[tpl[0]][tpl[1]]['correlation']) for tpl in G1.edges()]

In [52]:

e = [(x, x) for x in G1.nodes()] 

G1.remove_edges_from(e)

In [53]:

number_of_layers = 2

In [54]:

coupling_strength = 300

In [55]:
SAM = np.asmatrix(SAM)

In [56]:

for node in range(len(filelabels)):
    for layer1 in range(number_of_layers):
        for layer2 in range(number_of_layers):
            if layer1 != layer2:
                SAM[node + len(filelabels)*layer1, node + len(filelabels)*layer2] = coupling_strength

In [57]:


S = np.sum(SAM, axis = 1)

In [58]:

d = np.zeros(2*len(filelabels))

In [59]:
for i in range(2*len(filelabels)):
    d[i] = 1/S[i]

In [60]:

D = np.diag([d[i] for i in range(2*len(filelabels))])

In [ ]:
T = np.dot(SAM, D) 
# T is the transition matrix; it is a left stochastic matrix (i.e., all entries are non-negative and each column sums to 1)

In [61]:

N = 2*len(filelabels)

In [62]:
from numpy import linalg as la

In [63]:
L = number_of_layers

In [64]:
K = len(filelabels)

In [65]:

T=np.dot(SAM,D) # Refresh matrix T
r=0.85 # (1 r) is the teleportation rate 
R=r*T+(1-r)/N*np.ones((N, N))
RLeigenvector=np.asmatrix(np.ones(N))
RLeigenvector=RLeigenvector.transpose() # Now RLeigenvector is a N*1 column vector
while la.norm(RLeigenvector - np.dot(R,RLeigenvector))>10** - 8: 
    RLeigenvector = np.dot(R,RLeigenvector) / la.norm(np.dot(R,RLeigenvector))
NRLeigenvector=RLeigenvector/np.sum(RLeigenvector) 
NRLeigenvector=NRLeigenvector.reshape((L,K))
rankPageRank=np.squeeze(np.asarray(np.sum(NRLeigenvector, axis=0))) 
print("PageRank done.")

PageRank done.


In [ ]:

print(rankPageRank)

In [86]:

PageRank = [(filelabels[i], rankPageRank[i]) for i in range(len(filelabels))]

In [ ]:

Sorted_PageRank = sorted(PageRank, key = lambda t: t[1], reverse = True)

In [ ]:

print(Sorted_PageRank)

In [66]:

def cos_sim(x,y):
    return dot(x, y)/(norm(x)*norm(y))

In [67]:

PageRank_1 = [(i, filelabels[i], rankPageRank[i]) for i in range(len(filelabels))]

In [68]:

Sorted_PageRank_1 = sorted(PageRank_1, key = lambda t: t[2], reverse = True)

In [ ]:

print(Sorted_PageRank_1)

In [69]:
from numpy import dot
from numpy.linalg import norm

In [86]:
Poem = []
Selected_lines = []
Cosine = []

In [87]:

for f in Sorted_PageRank_1:
    v1 = []
    for j in vectors_of_lines[f[0]]:
        v1.append((j[0], cos_sim(poem_meter[36], j[1])))
    Cosine.append(v1)
    V = []
    V = sorted(v1, key = lambda t: t[1], reverse = True)
    Selected_lines.append((f[0], f[1], V[0][0]))
    i = V[0][0]
    Poem.append(lines[f[0]][i])

In [88]:

Mirror_Poem = []

In [89]:

for i in range(len(filelabels)):
    v2 = []
    for j in vectors_of_lines[i]:
        v2.append((j[0], cos_sim(poem_meter[36], j[1])))
    S = sorted(v2, key = lambda t: t[1], reverse = True)
    if len(S) >= 2:
        j = S[1][0]
    else:
        j = S[0][0]
    Mirror_Poem.append(lines[i][j])

In [90]:

for i in range(len(Poem)):
    print(Poem[i], '\t ', Mirror_Poem[i])

a poem says, “no, no. you have feelings. you have fears. you / have questions. let’s get back to the voice and the vocabulary of being human.” 	  annalynne mccord has recited a poem to president putin
celebrities go full cringe responding to russia's invasion of ukraine 	  his 'crime' – the poem 'to ukrainian patriots' in which he expresses / his opposition to russia's annexation of crimea and suggests ukrainians
russian poet sentenced over poem in support of ukraine 	  russia's war on ukraine, in context | the new yorker
he armed conflict in the east of ukraine brought about an emergence of a distinctive trend in contemporary ukrainian lit, the poetry of war 	  biden vows putin, russia will 'bear the consequences' after ukraine invasion
tributes flow for ' giant, no nonsense ' feminist author, educator, activist and poet bell hooks 	  khersonska also translates english-language poets into russian, including
myroslav laiuk is a ukrainian novelist, dramatist, ... many of whom were actua